In [60]:
import pandas as pd

In [61]:
# READ DATA
df = pd.read_excel('Data Mentah.xlsx')
df = pd.DataFrame(df)
df.info()
# print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1163 entries, 0 to 1162
Data columns (total 72 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   No.                                          1163 non-null   int64
 1   Tanggal                                      1163 non-null   object
 2   Nama Pasien                                  1163 non-null   object
 3   No. eRM                                      1163 non-null   int64
 4   NIK                                          902 non-null    float64
 5   No. RM Lama                                  466 non-null    object
 6   No. Dokumen RM                               1100 non-null   object
 7   Jenis Kelamin                                1163 non-null   object
 8   No Telp                                      1160 non-null   float64
 9   Alamat                                       22 non-null     object
 10  RT                                           14 non-null     float64
 11  RW                                           14 non-null     float64
 12  Pekerjaan                                    481 non-null    object
 13  Tanggal Pemeriksaan                          1163 non-null   object
 14  Kelurahan                                    1139 non-null   object
 15  Tempat Lahir                                 535 non-null    object
 16  Tgl.Lahir                                    1163 non-null   object
 17  Umur Tahun                                   1163 non-null   object
 18  Umur Bulan                                   1163 non-null   object
 19  Umur Hari                                    1163 non-null   object
 20  Nama Ayah                                    1 non-null      object
 21  Nama Ibu                                     0 non-null      float64
 22  Jenis Kunjungan                              1163 non-null   object
 23  Poli/Ruangan                                 1163 non-null   object
 24  Asuransi                                     1163 non-null   object
 25  No. Asuransi                                 1135 non-null   float64
 26  Dokter / Tenaga Medis                        1163 non-null   object
 27  Perawat / Bidan / Nutrisionist / Sanitarian  1086 non-null   object
 28  Keluhan Utama                                1163 non-null   object
 29  Keluhan Tambahan                             1 non-null      object
 30  Lama Sakit                                   1163 non-null   object
 31  Merokok                                      1163 non-null   object
 32  Konsumsi Alkohol                             1163 non-null   object
 33  Kurang Sayur/Buah                            1163 non-null   object
 34  Terapi                                       0 non-null      float64
 35  Keterangan                                   0 non-null      float64
 36  RPS                                          2 non-null      object
 37  RPD                                          2 non-null      object
 38  RPK                                          2 non-null      object
 39  Alergi                                       1096 non-null   object
 40  Kesadaran                                    1163 non-null   object
 41  Triage                                       1163 non-null   object
 42  Tinggi                                       1163 non-null   object
 43  Berat Badan                                  1163 non-null   object
 44  Lingkar Perut                                415 non-null    object
 45  IMT                                          1163 non-null   float64
 46  Hasil IMT                                    1163 non-null   object
 47  Sistole                                      1163 non-null   object
 48  Diastole                                     1163 non-null   object
 49  Nafas                                        1163 non-null   object
 50  Detak Nadi                                   1163 non-null   object
 51  Detak Jantung                                1163 non-null   object
 52  Suhu                                         470 non-null    object
 53  Aktifitas Fisik                              0 non-null      float64
 54  Diagnosa 1                                   1163 non-null   object
 55  Jenis Kasus 1                                1163 non-null   object
 56  Diagnosa 2                                   580 non-null    object
 57  Jenis Kasus 2                                580 non-null    object
 58  Diagnosa 3                                   98 non-null     object
 59  Jenis Kasus 3                                98 non-null     object
 60  Diagnosa 4                                   14 non-null     object
 61  Jenis Kasus 4                                14 non-null     object
 62  Diagnosa 5                                   2 non-null      object
 63  Jenis Kasus 5                                2 non-null      object
 64  Tindakan                                     10 non-null     object
 65  Resep                                        404 non-null    object
 66  Apoteker                                     404 non-null    object
 67  Pendaftaran/Rujukan Internal                 1163 non-null   object
 68  Lama Antrean                                 1163 non-null   object
 69  Lama Pemeriksaan                             1163 non-null   object
 70  Lama Pelayanan Obat                          1163 non-null   object
 71  Petugas Pendaftaran                          1163 non-null   object
dtypes: float64(10), int64(2), object(60)
memory usage: 654.3+ KB

In [62]:
for i in range(72):
    print(df.iloc[:, i:i+1].value_counts(), '\n')

No.
1       1
800     1
780     1
779     1
778     1
       ..
388     1
387     1
386     1
385     1
1163    1
Name: count, Length: 1163, dtype: int64

Tanggal
2021-10-30 00:00:00    2
2021-11-30 00:00:00    2
2021-01-02 00:00:00    1
2021-12-18 20:09:01    1
2021-12-20 10:02:46    1
                      ..
2021-07-05 08:30:13    1
2021-07-03 09:54:26    1
2021-07-02 08:39:28    1
2021-07-01 09:40:41    1
2022-04-20 10:48:31    1
Name: count, Length: 1161, dtype: int64

Nama Pasien
PAINI YULI ASTUTIK    17
JUMAIYAH              16
RIYANI                16
NUR HERMAJI           15
ROHMAH                15
                      ..
SUDAR                  1
ST HALIMATUS S         1
SRIYATI                1
SRI SUNARTI            1
YUSIANI                1
Name: count, Length: 324, dtype: int64

No. eRM
492187     17
143414     15
14668      15
13121      14
299612     12
           ..
250264      1
266627      1
272127      1
281960      1
669612      1
Name: count, Length: 336, dtype: int64

NIK
3.578094e+15    17
3.516086e+15    15
3.516082e+15    15
4.676769e+15    14
3.516081e+15    12
                ..
3.516081e+14     1
3.516085e+15     1
3.516084e+15     1
3.516084e+15     1
3.516085e+15     1
Name: count, Length: 227, dtype: int64

No. RM Lama
P351608018100866    15
P351608018001998    14
P351608018000666    12
P351608018103358    12
P351608018003426    12
                    ..
P351608018003146     1
P351608018003278     1
P351608018100368     1
P351608018100386     1
P351608018002632     1
Name: count, Length: 112, dtype: int64

No. Dokumen RM
011641            17
000071            15
008707            15
001758            14
000540            14
                  ..
011500             1
008068             1
003307             1
003252             1
002550             1
Name: count, Length: 290, dtype: int64

Jenis Kelamin
P                758
L                405
Name: count, dtype: int64

No Telp
0.000000e+00    213
8.523473e+10     35
8.564891e+10     24
8.151524e+10     20
8.952259e+10     17
               ...
8.581088e+10      1
8.223223e+10      1
8.581572e+10      1
8.573375e+10      1
8.570721e+10      1
Name: count, Length: 218, dtype: int64

Alamat
Pekukuhan        8
KEBONDALEM       5
BELAHANTENGAH    3
NGENGOR          1
NGROWO           1
PULOREJO         1
RANDUBANGO       1
gusten           1
margorejo        1
Name: count, dtype: int64

RT
25.0    5
19.0    3
2.0     1
4.0     1
5.0     1
6.0     1
7.0     1
10.0    1
Name: count, dtype: int64

RW
6.0    9
2.0    2
1.0    1
3.0    1
4.0    1
Name: count, dtype: int64

Pekerjaan
BELUM/TIDAK BEKERJA           262
WIRASWASTA                     84
PENSIUNAN                      37
MENGURUS RUMAH TANGGA          32
PEGAWAI NEGERI SIPIL (PNS)     29
KARYAWAN SWASTA                14
BURUH TANI/PERKEBUNAN          11
PETERNAK                        5
TUKANG BATU                     4
KEPALA DESA                     2
PETANI/PERKEBUNAN               1
Name: count, dtype: int64

Tanggal Pemeriksaan
2021-01-02 09:08:15    1
2021-12-27 10:32:29    1
2021-12-20 11:03:05    1
2021-12-20 10:31:37    1
2021-12-20 09:27:04    1
                      ..
2021-07-05 09:05:24    1
2021-07-03 09:55:21    1
2021-07-02 09:12:08    1
2021-07-01 09:54:18    1
2022-04-20 10:55:43    1
Name: count, Length: 1163, dtype: int64

Kelurahan
MODOPURO         221
KEBONDALEM       197
NGIMBANGAN       136
PEKUKUHAN        135
MENANGGAL        106
KEDUNGGEMPOL      77
JOTANGAN          71
LEMINGGIR         52
RANDUBANGO        40
MEJOYO            29
MOJOTAMPING       13
BANGSAL           11
NGARJO            10
KWATU              9
GEBANG MALANG      6
NGASTEMI           5
KUTOREJO           5
SALEN              4
BELAHANTENGAH      3
PEKUWON            2
PUNGGING           2
MARGOREJO          1
NGROWO             1
JASEM              1
PULOREJO           1
BALONGBENDO        1
Name: count, dtype: int64

Tempat Lahir
MOJOKERTO       505
SURABAYA         15
MALANG            4
MOJOKERO          4
MOJOKEERTO        2
SIDOARJO          2
GROBOGAN          1
KEDIRI            1
MJK               1
Name: count, dtype: int64

Tgl.Lahir
1954-12-31    29
1965-08-17    17
1978-11-17    15
1962-07-15    15
1968-03-10    14
              ..
1963-11-10     1
1963-12-30     1
1936-05-22     1
1964-10-12     1
2001-06-03     1
Name: count, Length: 312, dtype: int64

Umur Tahun
60 Tahun      60
56 Tahun      59
50 Tahun      57
61 Tahun      55
53 Tahun      54
63 Tahun      54
52 Tahun      52
66 Tahun      49
62 Tahun      47
55 Tahun      46
64 Tahun      45
51 Tahun      45
49 Tahun      43
58 Tahun      43
59 Tahun      37
54 Tahun      31
57 Tahun      27
48 Tahun      25
69 Tahun      24
67 Tahun      22
65 Tahun      18
42 Tahun      17
73 Tahun      17
47 Tahun      17
75 Tahun      16
44 Tahun      16
38 Tahun      16
71 Tahun      15
70 Tahun      15
46 Tahun      15
45 Tahun      14
68 Tahun      14
41 Tahun      13
43 Tahun      11
72 Tahun      10
74 Tahun       9
76 Tahun       8
81 Tahun       8
80 Tahun       8
37 Tahun       6
84 Tahun       5
32 Tahun       3
85 Tahun       2
31 Tahun       2
82 Tahun       2
24 Tahun       2
79 Tahun       1
20 Tahun       1
77 Tahun       1
40 Tahun       1
39 Tahun       1
34 Tahun       1
33 Tahun       1
25 Tahun       1
93 Tahun       1
Name: count, dtype: int64

Umur Bulan
10 Bulan      116
2 Bulan       111
5 Bulan       105
7 Bulan       104
4 Bulan       101
0 Bulan        99
11 Bulan       96
3 Bulan        92
6 Bulan        88
1 Bulan        84
9 Bulan        84
8 Bulan        83
Name: count, dtype: int64

Umur Hari
16 Hari      52
10 Hari      51
0 Hari       48
15 Hari      48
8 Hari       48
9 Hari       46
12 Hari      45
3 Hari       44
6 Hari       42
17 Hari      41
19 Hari      41
14 Hari      40
18 Hari      39
7 Hari       39
4 Hari       39
21 Hari      37
1 Hari       37
11 Hari      35
13 Hari      35
27 Hari      34
22 Hari      33
24 Hari      33
23 Hari      33
20 Hari      33
2 Hari       33
5 Hari       30
26 Hari      29
29 Hari      28
28 Hari      26
25 Hari      24
30 Hari      20
Name: count, dtype: int64

Nama Ayah
M.IMRON      1
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

Jenis Kunjungan
LAMA               1116
BARU                 47
Name: count, dtype: int64

Poli/Ruangan
POLI UMUM               970
POLI LANSIA             108
Layanan Poskesdes        67
PONKESDES NGIMBANGAN     11
Layanan Pustu             3
POLI KIA                  3
Layanan Pusling           1
Name: count, dtype: int64

Asuransi
BPJS Kesehatan    1127
Umum                28
Gratis               8
Name: count, dtype: int64

No. Asuransi
7.868727e+08    17
2.415520e+09    15
1.830606e+09    15
9.853219e+07    14
9.883750e+07    12
                ..
7.256186e+08     1
7.257357e+08     1
7.258856e+08     1
7.259199e+08     1
7.265326e+08     1
Name: count, Length: 313, dtype: int64

Dokter / Tenaga Medis
DR. NAILUL MAGHFIROH         1162
dr. PRAHARA WAHYU PURNOMO       1
Name: count, dtype: int64

Perawat / Bidan / Nutrisionist / Sanitarian
Yoyon Dayanto, S.Kep.Ns                        566
RUKIYAH                                        255
NINIS WAHYUNI. S.Kep.Ns                        223
Deni Kriswanto, Amd.Kep                         16
Dyah Susanti, Amd.Keb                           14
NUR RAKHMADILLA O,S.Kep.Ns                       3
AYU LITANIA                                      2
Hendrawati, SW, Amd. Keb                         2
Noviliyah, Amd.Kep                               2
Riayah, Amd.Keb                                  2
WIDYANTO,Amd.Kep                                 1
Name: count, dtype: int64

Keluhan Utama
Kontrol                                                571
SERING BAK PD MLM HARI                                  29
Pusing                                                  26
KONTROL                                                 23
Badan Sakit Semua                                       20
                                                      ...
Kaki Kiri Keluar Nanah                                   1
Kaki Kiri Ada Luka,batuk                                 1
Kaki Kesemutan,sulit Berjalan,nafas Agak Ngongsrong      1
Kaki Keselo,bengkak                                      1
Ujung Jari Terasa Kesemutan                              1
Name: count, Length: 392, dtype: int64

Keluhan Tambahan
Sakit Gigi,         1
Name: count, dtype: int64

Lama Sakit
2 Hari        572
3 Hari        248
1 Hari        167
0 Hari        118
4 Hari         15
7 Hari         13
5 Hari         12
6 Hari          6
30 Hari         3
8 Hari          3
14 Hari         2
10 Hari         1
20 Hari         1
21 Hari         1
300 Hari        1
Name: count, dtype: int64

Merokok
Tidak      1163
Name: count, dtype: int64

Konsumsi Alkohol
Tidak               1163
Name: count, dtype: int64

Kurang Sayur/Buah
Tidak                1163
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

Series([], Name: count, dtype: int64)

RPS
Tidak ada    2
Name: count, dtype: int64

RPD
Tidak ada    2
Name: count, dtype: int64

RPK
Tidak ada    2
Name: count, dtype: int64

Alergi
Obat : null,null,null,null,null,                                                                                                                                                                      126
Obat : null,                                                                                                                                                                                          122
Obat : null,null,                                                                                                                                                                                     114
Obat : null,null,null,null,                                                                                                                                                                            87
Obat : null,null,null,null,null,null,null,                                                                                                                                                             87
Obat : null,null,null,                                                                                                                                                                                 87
Obat : null,null,null,null,null,null,                                                                                                                                                                  74
Obat : null,null,null,null,null,null,null,null,null,                                                                                                                                                   56
Obat : null,null,null,null,null,null,null,null,null,null,null,                                                                                                                                         50
Obat : null,null,null,null,null,null,null,null,                                                                                                                                                        50
Obat : null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                                    42
Obat : null,null,null,null,null,null,null,null,null,null,                                                                                                                                              36
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                               19
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                           18
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                          18
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                       14
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                11
Obat : null,                                                                                                                                                                                           10
Obat : null,null,null,null,null,                                                                                                                                                                        8
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                             7
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                      7
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                       6
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,        5
Obat : null,null,null,null,null,null,                                                                                                                                                                   5
Obat : null,null,null,null,                                                                                                                                                                             5
Obat : null,null,null,                                                                                                                                                                                  5
Obat : null,null,null,null,null,null,null,                                                                                                                                                              4
Obat : null,null,null,null,null,null,null,null,null,                                                                                                                                                    3
Obat : null,null,null,null,null,null,null,null,                                                                                                                                                         3
Obat : null,null,                                                                                                                                                                                       3
                                                                                                                                                                                                        3
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                  2
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                                2
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                      1
Obat : null,null,null,null,null,null,null,null,null,null,                                                                                                                                               1
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                 1
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                      1
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                           1
Obat : null,null,null,null,null,null,null,null,null,null,null,null,                                                                                                                                     1
Obat : null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,        1
Name: count, dtype: int64

Kesadaran
COMPOS MENTIS    1163
Name: count, dtype: int64

Triage
TIDAK GAWAT DARURAT    1163
Name: count, dtype: int64

Tinggi
158 cm    621
155 cm    173
160 cm     58
150 cm     56
165 cm     53
170 cm     50
168 cm     21
159 cm     20
157 cm     18
156 cm     15
175 cm     11
153 cm      7
164 cm      7
167 cm      7
152 cm      6
162 cm      6
163 cm      6
148 cm      5
154 cm      4
166 cm      3
169 cm      3
172 cm      2
173 cm      2
58 cm       2
145 cm      2
147 cm      2
146 cm      2
110 cm      1
Name: count, dtype: int64

Berat Badan
56 kg          496
55 kg          187
60 kg          166
65 kg           81
50 kg           51
58 kg           25
70 kg           23
57 kg           23
45 kg           15
67 kg            9
54 kg            8
68 kg            7
63 kg            6
47 kg            6
59 kg            5
66 kg            5
62 kg            5
53 kg            5
52 kg            4
69 kg            4
80 kg            4
75 kg            3
90 kg            3
40 kg            3
48 kg            3
46 kg            3
64 kg            2
49 kg            2
44 kg            2
609 kg           1
74 kg            1
76 kg            1
78 kg            1
79 kg            1
43 kg            1
25 kg            1
Name: count, dtype: int64

Lingkar Perut
80 cm            257
90 cm             34
88 cm             30
100 cm            17
98 cm             15
120 cm            10
110 cm             5
68 cm              4
74 cm              4
105 cm             3
76 cm              3
94 cm              3
84 cm              3
89 cm              3
57 cm              2
115 cm             2
96 cm              2
82 cm              2
64 cm              2
130 cm             2
125 cm             2
93 cm              1
97 cm              1
95 cm              1
85 cm              1
135 cm             1
72 cm              1
70 cm              1
55 cm              1
66 cm              1
99 cm              1
Name: count, dtype: int64

IMT
22.43     439
22.03     128
24.97      44
23.31      31
22.04      26
         ...
21.00       1
24.02       1
24.00       1
23.95       1
237.89      1
Name: count, Length: 160, dtype: int64

Hasil IMT
IDEAL           1057
LEBIH             88
KURANG             9
GEMUK              6
SANGAT GEMUK       3
Name: count, dtype: int64

Sistole
130 mm     442
120 mm     283
140 mm      87
110 mm      80
150 mm      43
          ...
116 mm       1
153 mm       1
163 mm       1
157 mm       1
91 mm        1
Name: count, Length: 78, dtype: int64

Diastole
80 Hg       606
70 Hg       216
90 Hg       116
60 Hg        70
100 Hg       31
89 Hg         8
86 Hg         8
79 Hg         7
85 Hg         6
88 Hg         6
83 Hg         5
87 Hg         5
76 Hg         5

In [63]:
print("\n", "MISSING VALUE".center(100, "="))
# print(df.isna().sum())
for i in range(72):
    print(df.iloc[:, i:i+1].isna().sum(), '\n')

 ===========================================MISSING VALUE============================================
No.    0
dtype: int64

Tanggal    0
dtype: int64

Nama Pasien    0
dtype: int64

No. eRM    0
dtype: int64

NIK    261
dtype: int64

No. RM Lama    697
dtype: int64

No. Dokumen RM    63
dtype: int64

Jenis Kelamin    0
dtype: int64

No Telp    3
dtype: int64

Alamat    1141
dtype: int64

RT    1149
dtype: int64

RW    1149
dtype: int64

Pekerjaan    682
dtype: int64

Tanggal Pemeriksaan    0
dtype: int64

Kelurahan    24
dtype: int64

Tempat Lahir    628
dtype: int64

Tgl.Lahir    0
dtype: int64

Umur Tahun    0
dtype: int64

Umur Bulan    0
dtype: int64

Umur Hari    0
dtype: int64

Nama Ayah    1162
dtype: int64

Nama Ibu    1163
dtype: int64

Jenis Kunjungan    0
dtype: int64

Poli/Ruangan    0
dtype: int64

Asuransi    0
dtype: int64

No. Asuransi    28
dtype: int64

Dokter / Tenaga Medis    0
dtype: int64

Perawat / Bidan / Nutrisionist / Sanitarian    77
dtype: int64

Keluhan Utama    0
dtype: int64

Keluhan Tambahan    1162
dtype: int64

Lama Sakit    0
dtype: int64

Merokok    0
dtype: int64

Konsumsi Alkohol    0
dtype: int64

Kurang Sayur/Buah    0
dtype: int64

Terapi    1163
dtype: int64

Keterangan    1163
dtype: int64

RPS    1161
dtype: int64

RPD    1161
dtype: int64

RPK    1161
dtype: int64

Alergi    67
dtype: int64

Kesadaran    0
dtype: int64

Triage    0
dtype: int64

Tinggi    0
dtype: int64

Berat Badan    0
dtype: int64

Lingkar Perut    748
dtype: int64

IMT    0
dtype: int64

Hasil IMT    0
dtype: int64

Sistole    0
dtype: int64

Diastole    0
dtype: int64

Nafas    0
dtype: int64

Detak Nadi    0
dtype: int64

Detak Jantung    0
dtype: int64

Suhu    693
dtype: int64

Aktifitas Fisik    1163
dtype: int64

Diagnosa 1    0
dtype: int64

Jenis Kasus 1    0
dtype: int64

Diagnosa 2    583
dtype: int64

Jenis Kasus 2    583
dtype: int64

Diagnosa 3    1065
dtype: int64

Jenis Kasus 3    1065
dtype: int64

Diagnosa 4    1149
dtype: int64

Jenis Kasus 4    1149
dtype: int64

Diagnosa 5    1161
dtype: int64

Jenis Kasus 5    1161
dtype: int64

Tindakan    1153
dtype: int64

Resep    759
dtype: int64

Apoteker    759
dtype: int64

Pendaftaran/Rujukan Internal    0
dtype: int64

Lama Antrean    0
dtype: int64

Lama Pemeriksaan    0
dtype: int64

Lama Pelayanan Obat    0
dtype: int64

Petugas Pendaftaran    0
dtype: int64

In [64]:
df = df.dropna(axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1163 entries, 0 to 1162
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   No.                           1163 non-null   int64
 1   Tanggal                       1163 non-null   object
 2   Nama Pasien                   1163 non-null   object
 3   No. eRM                       1163 non-null   int64
 4   Jenis Kelamin                 1163 non-null   object
 5   Tanggal Pemeriksaan           1163 non-null   object
 6   Tgl.Lahir                     1163 non-null   object
 7   Umur Tahun                    1163 non-null   object
 8   Umur Bulan                    1163 non-null   object
 9   Umur Hari                     1163 non-null   object
 10  Jenis Kunjungan               1163 non-null   object
 11  Poli/Ruangan                  1163 non-null   object
 12  Asuransi                      1163 non-null   object
 13  Dokter / Tenaga Medis         1163 non-null   object
 14  Keluhan Utama                 1163 non-null   object
 15  Lama Sakit                    1163 non-null   object
 16  Merokok                       1163 non-null   object
 17  Konsumsi Alkohol              1163 non-null   object
 18  Kurang Sayur/Buah             1163 non-null   object
 19  Kesadaran                     1163 non-null   object
 20  Triage                        1163 non-null   object
 21  Tinggi                        1163 non-null   object
 22  Berat Badan                   1163 non-null   object
 23  IMT                           1163 non-null   float64
 24  Hasil IMT                     1163 non-null   object
 25  Sistole                       1163 non-null   object
 26  Diastole                      1163 non-null   object
 27  Nafas                         1163 non-null   object
 28  Detak Nadi                    1163 non-null   object
 29  Detak Jantung                 1163 non-null   object
 30  Diagnosa 1                    1163 non-null   object
 31  Jenis Kasus 1                 1163 non-null   object
 32  Pendaftaran/Rujukan Internal  1163 non-null   object
 33  Lama Antrean                  1163 non-null   object
 34  Lama Pemeriksaan              1163 non-null   object
 35  Lama Pelayanan Obat           1163 non-null   object
 36  Petugas Pendaftaran           1163 non-null   object
dtypes: float64(1), int64(2), object(34)
memory usage: 336.3+ KB

In [65]:
# print("\n", "MISSING VALUE".center(100, "="))
# # print(df.isna().sum())
# for i in range(37):
#     print(df.iloc[:, i:i+1].isna().sum(), '\n')

In [66]:
# df['Sistole'] = df['Sistole'].str.replace(' mm', '')
# df['Diastole'] = df['Diastole'].str.replace(' Hg', '')

In [67]:
# print(df.iloc[:, 0:1])

In [68]:
y = df['Hasil IMT']
# X = df.drop(['Hasil IMT'], axis = 1)
X = df[['Jenis Kelamin', 'Umur Tahun', 'Lama Sakit', 'Tinggi', 'Berat Badan', 'IMT']]

In [69]:
X['Jenis Kelamin'] = X['Jenis Kelamin'].str.replace('L', '0')
X['Jenis Kelamin'] = X['Jenis Kelamin'].str.replace('P', '1')
X['Umur Tahun'] = X['Umur Tahun'].str.replace(' Tahun', '')
X['Lama Sakit'] = X['Lama Sakit'].str.replace(' Hari', '')
X['Tinggi'] = X['Tinggi'].str.replace(' cm', '')
X['Berat Badan'] = X['Berat Badan'].str.replace(' kg', '')
# df['Diastole'] = df['Diastole'].str.replace(' Hg', '')

C:\Users\INES\AppData\Local\Temp\ipykernel_8244\865164383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Jenis Kelamin'] = X['Jenis Kelamin'].str.replace('L', '0')
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\865164383.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Jenis Kelamin'] = X['Jenis Kelamin'].str.replace('P', '1')
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\865164383.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Umur Tahun'] = X['Umur Tahun'].str.replace(' Tahun', '')
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\865164383.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Lama Sakit'] = X['Lama Sakit'].str.replace(' Hari', '')
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\865164383.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Tinggi'] = X['Tinggi'].str.replace(' cm', '')
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\865164383.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Berat Badan'] = X['Berat Badan'].str.replace(' kg', '')

In [70]:
import numpy as np

outliers = []
def detect_outlier(data):
    threshold = 3
    mean = np.mean(data)
    std = np.std(data)
    
    for y in data:
        z_score = (y-mean)/std
        if np.abs(z_score)>threshold:
            outliers.append(y)
    return outliers

X['Tinggi'] = X['Tinggi'].astype(float)
outlier_tinggi = detect_outlier(X['Tinggi'])
print('Outlier Tinggi Badan = ', outlier_tinggi)
outliers.clear()

X['Berat Badan'] = X['Berat Badan'].astype(float)
outlier_berat = detect_outlier(X['Berat Badan'])
print('Outlier Berat Badan = ', outlier_berat)
outliers.clear()

Outlier Tinggi Badan =  [58.0, 58.0, 110.0]
Outlier Berat Badan =  [609.0]

C:\Users\INES\AppData\Local\Temp\ipykernel_8244\972225750.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Tinggi'] = X['Tinggi'].astype(float)
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\972225750.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Berat Badan'] = X['Berat Badan'].astype(float)

In [71]:
X.drop(index=outlier_tinggi, inplace=True)
X.drop(index=outlier_berat, inplace=True)

C:\Users\INES\AppData\Local\Temp\ipykernel_8244\3496500095.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(index=outlier_tinggi, inplace=True)
C:\Users\INES\AppData\Local\Temp\ipykernel_8244\3496500095.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(index=outlier_berat, inplace=True)

In [72]:
# from sklearn.preprocessing import OneHotEncoder

# encoder = OneHotEncoder()
# results = encoder.fit_transform(X[["Jenis Kelamin"]])
# pd.DataFrame(results.toarray(), columns=encoder.categories_).head()
print(X.dtypes)

Jenis Kelamin     object
Umur Tahun        object
Lama Sakit        object
Tinggi           float64
Berat Badan      float64
IMT              float64
dtype: object

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=100, test_size=0.3)

In [74]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

model=SVC()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

print("HASIL PREDIKSI SVM")
print(y_pred)
print("HASIL CONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))
print("HASIL AKURASI PEMODELAN SVM:", accuracy_score(y_test, y_pred))

HASIL PREDIKSI SVM
['IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL']
HASIL CONFUSION MATRIX
[[  0   2   0   1]
 [  0 316   0   0]
 [  0   5   0   0]
 [  0  25   0   0]]
HASIL AKURASI PEMODELAN SVM: 0.9054441260744985

In [79]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

model = GaussianNB()

# Train the classifier:
model.fit(X_train, y_train)
# Make predictions with the classifie
y_pred=model.predict(X_test)
print(y_pred)

# Evaluate label (subsets) accuracy:
print("HASIL CONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))
print("HASIL AKURASI PEMODELAN NB:", accuracy_score(y_test, y_pred))

['IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'KURANG' 'LEBIH' 'LEBIH'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'KURANG' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL'
 'IDEAL' 'IDEAL' 'LEBIH' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'LEBIH'
 'IDEAL' 'SANGAT GEMUK' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'LEBIH' 'IDEAL' 'IDEAL' 'KURANG' 'LEBIH' 'KURANG' 'IDEAL' 'IDEAL' 'IDEAL'
 'LEBIH' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'LEBIH' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH'
 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'LEBIH' 'GEMUK' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'KURANG'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'KURANG' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'LEBIH' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH'
 'IDEAL' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'GEMUK' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'LEBIH'
 'LEBIH' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL'
 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL' 'IDEAL']
HASIL CONFUSION MATRIX
[[  1   0   0   2   0]
 [  0 305   1   9   1]
 [  0   0   5   0   0]
 [  1   0   0  24   0]
 [  0   0   0   0   0]]
HASIL AKURASI PEMODELAN NB: 0.9598853868194842

In [ ]:
# import matplotlib.pyplot as plt
# import seaborn as sns
# cor = X_train.corr()
# plt.figure(figsize=(12,10))
# sns.heatmap(cor, cmap=plt.cm.CMRmap_r,annot=True)
# plt.show()

In [ ]:
# def correlation(dataset, threshold):
#     col_corr = set()
#     corr_matrix = dataset.corr()
#     for i in range(len(corr_matrix.columns)):
#         for j in range(i):
#             if abs(corr_matrix.iloc[i, j]) > threshold: colname = corr_matrix.columns[i]                  
#     col_corr.add(corr_matrix.columns[i] )
#     return col_corr

# corr_features = correlation(X_train, 0.7)
# corr_features